// Generated by gencpp from file my_robot/DriveToTarget.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MESSAGE_DRIVETOTARGET_H
#define MY_ROBOT_MESSAGE_DRIVETOTARGET_H

#include <ros/service_traits.h>


#include <my_robot/DriveToTargetRequest.h>
#include <my_robot/DriveToTargetResponse.h>


namespace my_robot
{

struct DriveToTarget
{

typedef DriveToTargetRequest Request;
typedef DriveToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveToTarget
} // namespace my_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot::DriveToTarget > {
  static const char* value()
  {
    return "c8652349d2a34a90a09475339e2a93d9";
  }

  static const char* value(const ::my_robot::DriveToTarget&) { return value(); }
};

template<>
struct DataType< ::my_robot::DriveToTarget > {
  static const char* value()
  {
    return "my_robot/DriveToTarget";
  }

  static const char* value(const ::my_robot::DriveToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot::DriveToTargetRequest> should match 
// service_traits::MD5Sum< ::my_robot::DriveToTarget > 
template<>
struct MD5Sum< ::my_robot::DriveToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot::DriveToTarget >::value();
  }
  static const char* value(const ::my_robot::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot::DriveToTargetRequest> should match 
// service_traits::DataType< ::my_robot::DriveToTarget > 
template<>
struct DataType< ::my_robot::DriveToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot::DriveToTarget >::value();
  }
  static const char* value(const ::my_robot::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot::DriveToTargetResponse> should match 
// service_traits::MD5Sum< ::my_robot::DriveToTarget > 
template<>
struct MD5Sum< ::my_robot::DriveToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot::DriveToTarget >::value();
  }
  static const char* value(const ::my_robot::DriveToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot::DriveToTargetResponse> should match 
// service_traits::DataType< ::my_robot::DriveToTarget > 
template<>
struct DataType< ::my_robot::DriveToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot::DriveToTarget >::value();
  }
  static const char* value(const ::my_robot::DriveToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MESSAGE_DRIVETOTARGET_H
